export const PRODUCT_NAME_SUFFIX_FOR_STAGE = {
    // keys are the `environment` field of files in phoenix repo: config.json, brackets.config.dist.json
    // and brackets.config.staging.json. The product name suffix corresponding to each stage are values.
    dev : "Experimental Build",
    stage: "Pre-release",
    production: "" // has no suffix
};

export const BUNDLE_IDENTIFIER_FOR_STAGE = {
    dev : "io.phcode.dev",
    stage: "io.phcode.staging",
    production: "io.phcode"
};

export const UPDATE_NOTIFICATION_LATEST_JSON_FILE_PATH = {
    // do not change any of these names unless you want to nuke the updater for all the whole installation base!!
    // or you know what you are doing.
    dev: "tauri/update-latest-experimental-build.json",
    stage: "tauri/update-latest-pre-release.json",
    production: "tauri/update-latest-stable-prod.json"
};

export const UPDATE_NOTIFICATIONS_BASE_URL = "https://updates.phcode.io/";

// latest.json file that is generated as part of tauri build in every GitHub release. it is generated by tauri build action.
export const LATEST_JSON_GITHUB_RELEASE = "latest.json";